### ISSUE TITLE
Can you modify the code for the new Facebook interactions?

### ISSUE THREAD

**Issue by jrosen48** [minimaxir/facebook-page-post-scraper#1]
Thanks for a great tool... Can you modify the code for the new Facebook interactions (i.e., Love it, Sad, etc.)?

**Comment by minimaxir** [comment]
Not yet. Coincidentally I am writing an angry blog post about exactly that.

**Comment by jrosen48** [comment]
Will look for it.


Sent from Outlook Mobile






On Sun, Feb 28, 2016 at 4:53 PM -0800, "Max Woolf" <notifications@github.com> wrote:












Not yet. Coincidentally I am writing an angry blog post about exactly that.

**Comment by andravasile** [comment]
Hello!

I am getting this error because I am trying to get the posts from a norwegian fb page... Could you please help me to fix it?

UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 52: ordinal not in range(128)

I tried to put this line at the beginning of my code, but it still does not work.

# -*- coding: utf-8 -*-

Thank you in advance!

**Comment by andravasile** [comment]
Hello!

I am getting this error because I am trying to get the posts from a norwegian fb page... Could you please help me to fix it?

UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 52: ordinal not in range(128)

I tried to put this line at the beginning of my code, but it still does not work.

-- coding: utf-8 --

Thank you in advance!

**Comment by minimaxir** [comment]
Support for reactions was added in v2.6...unfortunately, not the count for each reaction. That will have to wait.

Script updated for count of all reactions.
