### ISSUE TITLE
Unable to scrape entire post list

### ISSUE THREAD

**Issue by Renevatia** [minimaxir/facebook-page-post-scraper#21]
Not sure if its indexing problem of FB api. Changing api version does not solve issue. Only happens on some pages, usually very large pages and typing in the url with app token shows missing posts on browser as well.

RiotGames, Redbull page extract will show the problem with incomplete scraping.

**Comment by minimaxir** [comment]
Running the script [RiotGames](https://www.facebook.com/RiotGames) retrieving all the posts, which can manually be verified since there were only 60. [leagueoflegends](https://www.facebook.com/leagueoflegends/) appear the same.

[Redbull](https://www.facebook.com/Redbull/) is weird and I am looking into it, as some of the posts in the output are not present.

**Comment by minimaxir** [comment]
Figured out the case of Red Bull. Turns out the privacy settings of some of their posts are not "public." These posts are indicated with a "cog" privacy setting instead of a "globe" setting.

<img width="504" alt="screen shot 2016-09-24 at 5 14 57 pm" src="https://cloud.githubusercontent.com/assets/2179708/18812014/a5f4bfde-827a-11e6-8f1d-d8cdcca58e44.png">

If you use your own `access_token` from the [Graph API Explorer](https://developers.facebook.com/tools/explorer/), those posts now appear in the output correctly.

It is unlikely I will be able to access those posts with the App Token trick. I'm not entirely sure what this semi-public state is anyways.

**Comment by Renevatia** [comment]
Thanks for the fast response. I will give that a try. It doesn't seem that most pages are using this kind of posts. I should have checked riotgames posts before assuming it's doing the same thing as redbull.
